### PR TITLE
Release: v2020.11.17

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 0828afc812477d0caed2470fcb5ab4b8e04789dd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/stash-enterprise 473534f4ea52cbc558fcecf49ee62b5923cac73b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli b9bac70048a37d9f0dd05deb812623cb0842a334

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 d8099e8274b200ecbd4776d92ff4eadfa9f98ddc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 32cd3b6c85afc2ce920a265d8e4eae021e6d4e72

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 1d17c0a0ddd2fee45eae6b638215ae1329761016

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 391e953f67e6e926c33beb3d0966772793f9001f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 5566a42f4e7b79e6815acf8ae3d9020e5bad9c99

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 5566a42f4e7b79e6815acf8ae3d9020e5bad9c99

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 2282e4e40acdbd75fd31f5b544d1b6cc8b8ebdbd
/chart github.com/stashed/elasticsearch 7.2.0-v4
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 446d984d75bd8774873fe729791944c3fa4217bc
/chart github.com/stashed/elasticsearch 7.3.2-v4
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 26bed367addd579c8c42d521a70fbee3b8d0bd23
/chart github.com/stashed/elasticsearch 5.6.4-v4
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 7ec358e3b69bec86d6062ffb6ff2e9cfa940f955
/chart github.com/stashed/elasticsearch 6.2.4-v4
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 eace801809826834df56040adaa74bb5b8581e29
/chart github.com/stashed/elasticsearch 6.3.0-v4
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 f33d141fb972ad06431e60f104fb3165f500d9c6
/chart github.com/stashed/elasticsearch 6.4.0-v4
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 26f57f3465f284720bc494681ded801dea226f77
/chart github.com/stashed/elasticsearch 6.5.3-v4
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 cf72bbe6d5a79eae63c27eeed2947def659f444b
/chart github.com/stashed/elasticsearch 6.8.0-v4
/tagged github.com/stashed/elasticsearch
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 391e953f67e6e926c33beb3d0966772793f9001f

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/postgres/pull/457
/go github.com/stashed/postgres stash.appscode.dev/postgres 
/pr https://github.com/stashed/postgres/pull/458
/pr https://github.com/stashed/postgres/pull/459
/ready-to-tag github.com/stashed/postgres 391e953f67e6e926c33beb3d0966772793f9001f
/pr https://github.com/stashed/postgres/pull/460
/ready-to-tag github.com/stashed/postgres 27fb41c7fbed3ac761459655dfb76925430c47e3

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 7ec358e3b69bec86d6062ffb6ff2e9cfa940f955
/chart github.com/stashed/elasticsearch 6.2.4-v4
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 eace801809826834df56040adaa74bb5b8581e29
/chart github.com/stashed/elasticsearch 6.3.0-v4
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 f33d141fb972ad06431e60f104fb3165f500d9c6
/chart github.com/stashed/elasticsearch 6.4.0-v4
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 26f57f3465f284720bc494681ded801dea226f77
/chart github.com/stashed/elasticsearch 6.5.3-v4
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 cf72bbe6d5a79eae63c27eeed2947def659f444b
/chart github.com/stashed/elasticsearch 6.8.0-v4
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 2282e4e40acdbd75fd31f5b544d1b6cc8b8ebdbd
/chart github.com/stashed/elasticsearch 7.2.0-v4
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 446d984d75bd8774873fe729791944c3fa4217bc
/chart github.com/stashed/elasticsearch 7.3.2-v4
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 26bed367addd579c8c42d521a70fbee3b8d0bd23
/chart github.com/stashed/elasticsearch 5.6.4-v4
/tagged github.com/stashed/elasticsearch
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 c3ad7736453e4ad64be7bc4965bc5efa1dab22da
/chart github.com/stashed/mongodb 4.0.5-v4
/cherry-picked github.com/stashed/mongodb release-4.1.13 35b1e19691cd4ee2d442cd077da35cecca4eff2d
/chart github.com/stashed/mongodb 4.1.13-v4
/cherry-picked github.com/stashed/mongodb release-4.1.4 91f1138b2ca923bd2bf34b4c3d1405fd401ccb09
/chart github.com/stashed/mongodb 4.1.4-v4
/cherry-picked github.com/stashed/mongodb release-3.4.17 de22e33d2fcd7a761a678b69588ae9d28534466c
/chart github.com/stashed/mongodb 3.4.17-v4
/cherry-picked github.com/stashed/mongodb release-3.4.22 669ea18708681f3b384ba226ab357bb405bb30b4
/chart github.com/stashed/mongodb 3.4.22-v4
/cherry-picked github.com/stashed/mongodb release-3.6.13 653462db27eb9fcbe213e7aa118f6e8f5f2b2634
/chart github.com/stashed/mongodb 3.6.13-v4
/cherry-picked github.com/stashed/mongodb release-4.1.7 99ab134b6e6d312dec797560bb4551c0af3a9c6a
/chart github.com/stashed/mongodb 4.1.7-v4
/cherry-picked github.com/stashed/mongodb release-4.2.3 b6056d71943afe5c845f563b0837a58d14551bd0
/chart github.com/stashed/mongodb 4.2.3-v4
/cherry-picked github.com/stashed/mongodb release-3.6.8 3ff979fca0b0392815944ea3528d66253d22e605
/chart github.com/stashed/mongodb 3.6.8-v4
/cherry-picked github.com/stashed/mongodb release-4.0.11 2b676e1bf440facbdc352d6506b18b69f46c6a17
/chart github.com/stashed/mongodb 4.0.11-v4
/cherry-picked github.com/stashed/mongodb release-4.0.3 c0fe6d6641583f7cc1dd9138c1a6760c203c2f3e
/chart github.com/stashed/mongodb 4.0.3-v4
/tagged github.com/stashed/mongodb
/go github.com/stashed/mongodb stash.appscode.dev/mongodb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 6f311932e9cda393fdd996c7a1e979de92831231
/chart github.com/stashed/mysql 5.7.25-v4
/cherry-picked github.com/stashed/mysql release-8.0.14 25d309b67d0fb5725ec3144e22c4310b5a4f6f2c
/chart github.com/stashed/mysql 8.0.14-v4
/cherry-picked github.com/stashed/mysql release-8.0.3 7dcd87c7fc595323d19a34cc48ba9c0515edccc8
/chart github.com/stashed/mysql 8.0.3-v4
/tagged github.com/stashed/mysql
/go github.com/stashed/mysql stash.appscode.dev/mysql

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 6f311932e9cda393fdd996c7a1e979de92831231
/chart github.com/stashed/mysql 5.7.25-v4
/cherry-picked github.com/stashed/mysql release-8.0.14 25d309b67d0fb5725ec3144e22c4310b5a4f6f2c
/chart github.com/stashed/mysql 8.0.14-v4
/cherry-picked github.com/stashed/mysql release-8.0.3 7dcd87c7fc595323d19a34cc48ba9c0515edccc8
/chart github.com/stashed/mysql 8.0.3-v4
/tagged github.com/stashed/mysql
/go github.com/stashed/mysql stash.appscode.dev/mysql

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/118
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/119

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 da7b589751304c310e1d39ca7f04a31fd9fa176b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 4decd7528ca19737c9fff3247ada0c4c9098c030

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 926a13e7397e27526672d789abd9310cea0ac185

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 0948b82b34179a5c64cf9694200c7867f0dc1026

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 fadf2d394d175a002db488e0a775f93de48ecc20

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/127
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 597f380cdea199cdc48584139bda16c64303d85a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/catalog 95f66289712f18b2dc3f2d845303353f181f3941

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 7aa0987e555a5b0029d4040883688f6da73a3be9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website c9dec33d3fba76a16c08f96e5c5e429d726b05cf

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles fba76de843c4b56dad2d788b0da6d8ed872e92f7

**Pull request merged**
