### PR TITLE
Release: v2021.03.17

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash b7700c299eac914edda2fe4ab008393284dfbec6

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/stash-enterprise 301bd05fbe8929929e34e81ee10f8060c9edff52

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli f1ca9e2e4ae1109d0af50a844d36e98af47104f6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 45ecd27f0a785a9da0c39215363cdf289fa3ff09

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 c08f7b4699f3619889e3c034a69351a9a16f2c57

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 edc152a32535b2ffb55ac703315ef0295f10e7af

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 7deba4284d31ab189d62a1f1678e32c34d0f507d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 30abe5deaa66c017bd0545cfb1b9ceafbf549897

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 30abe5deaa66c017bd0545cfb1b9ceafbf549897

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 5049703e5493605948bbc693494fa37ce32b15bd
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 ecf08141cecf55852fb08d2ee807d3c1dd29193b
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 012960390484d2e541329c223619ba95fd3c3806
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 8338d91aed3d32ef6acaf960ab8f7c29b8612ced
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 aeb2f5362dff870cd4d4bcbd7657d296dd706066
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 add4048e18a8cb816ab2bb6b0a52f199e7ada562
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 1468b55f761c5c40ece8ea8636ee253656c4db8c
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 29979aa92559ab2a9e4a6fbf767aeba1da91d155
/tagged github.com/stashed/elasticsearch
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 d83060a9188556670968e7e07b900ccca3938b6d
/cherry-picked github.com/stashed/mongodb release-3.4.17 665a6f42965580f19e65031f775b6837042cccb8
/cherry-picked github.com/stashed/mongodb release-3.4.22 681f6ea9eb0bd7625574c780b65ace222aae4dfe
/cherry-picked github.com/stashed/mongodb release-4.0.11 34b8968e366ed24878394ee2243f2a07cee46623
/cherry-picked github.com/stashed/mongodb release-4.0.3 ff42b4292aaa0b6ce64c8d1ea6264d31747b8dda
/cherry-picked github.com/stashed/mongodb release-4.0.5 1c62f150648c955b30276fddf9415ddffd848ac2
/cherry-picked github.com/stashed/mongodb release-4.1.13 eff2f04f2b287b91144fdb4208bfe377a5e7b873
/cherry-picked github.com/stashed/mongodb release-4.1.4 a049bcb8e877cad93a3f02b31ee6fe745e8d9c41
/cherry-picked github.com/stashed/mongodb release-3.6.13 009b35e2849a1f8bad38db72a486dd1df3d53c41
/cherry-picked github.com/stashed/mongodb release-3.6.8 5ee30be0f762b9769fdb0818222652ff26e77d5e
/cherry-picked github.com/stashed/mongodb release-4.2.3 44c1cdb2e850cb826e1773733273d6d0508576a2
/tagged github.com/stashed/mongodb
/go github.com/stashed/mongodb stash.appscode.dev/mongodb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 4e7c41e664ea90adb6d9ce629a170f72a2bb103e
/cherry-picked github.com/stashed/mysql release-8.0.14 40b763ea896da1018f66e6e8fe4eb698b03236c6
/cherry-picked github.com/stashed/mysql release-8.0.21 4b31e35cfdb2de76255dce55844a74361da1f45e
/cherry-picked github.com/stashed/mysql release-8.0.3 2f047cfafb58778eaae73b0748a98da54b03f6d9
/tagged github.com/stashed/mysql
/go github.com/stashed/mysql stash.appscode.dev/mysql

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 b7b6fa4ef33852c08d1eb987d6721bda498e8238
/tagged github.com/stashed/mariadb
/go github.com/stashed/mariadb stash.appscode.dev/mariadb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 3fee29dcf70d2f308f18f67107bc1e51325b0c34
/tagged github.com/stashed/percona-xtradb
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/166
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer adbca35e34094bf2fb8c66429e82e57eda32fa28

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs eea9d6a17bd3db564b87f83896ef174608cd0060

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website 080194de9bc31d1b522b0b893857dfff86db4ffb

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 8ba84b632dbceacb1d70074285c52c5db388ddbb

**Pull request merged**
