### PR TITLE
Release: v2022.02.22

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 9536bc1b41a8e217f2db1d09051b6edc8b0e975b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise fcf0f4f51808dcff0715c57903cdd55ddbd0156e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/ui-server e2ce681d19d50d1e93dc82dd20b65d185d44a423

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 938c3f3a9f1000a6c16c797061148fadfe8d600e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 91c7414d92304f09621b45c5022977c7d78403ed

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 6335e10e583e7b493f6238b085bd02b7558c6366

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 2e928b1bdb093c10605932cf8975ba6bd39b1f97

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 2813a98a333d1f4f5865cdaabb992f8fe26687ea

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/elasticsearch/pull/1097
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/pr https://github.com/stashed/elasticsearch/pull/1098
/pr https://github.com/stashed/elasticsearch/pull/1099
/pr https://github.com/stashed/elasticsearch/pull/1100
/pr https://github.com/stashed/elasticsearch/pull/1101
/pr https://github.com/stashed/elasticsearch/pull/1102
/pr https://github.com/stashed/elasticsearch/pull/1103
/pr https://github.com/stashed/elasticsearch/pull/1104
/pr https://github.com/stashed/elasticsearch/pull/1105
/pr https://github.com/stashed/elasticsearch/pull/1106

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 885a5c59f212c85ab433c4c1078882fa8d2d2b07

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 5eafa076a57674ea2932afb92ae9ffd72f41a0d0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 ab9c11e58a11c4321097222631c0bd45c33f8dfa

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 811094fc0c063756372cc8515e264c2201aaefbb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 b78c499d01f442fda28135c5cbe04af68af72cf0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 7a7c194d3c3714dd29c4c700886a49b6c543da1e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 c351d557fbdf0885f2f0d156b0a1191db8f3432b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 256947cb69afb3f4b6a0f09bf25938c9725aad88

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 257c67834cabee560a442da456277a298b22c2e4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 7fdea5acc09dc7698c81d8ce8b53edb9f2107b47

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 8014a998b5fe04e18bd0e9ff14d5d71f99bcbb8b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 9a366c96c5f0cd6e90be5163c8b6ea8542d85eb5

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 d081d8c225e81297fe530c5ef0181a9f85dc30ab

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 e2fc99c1eff1734076ef314b289aa40c1a86c71a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 ce6044eb56367c5dcb24da292ba7044bbc870c1d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 fe2ff6dc6b3c5c7f9184f4a9ba7a560e9ef079a9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 b7533ecbf0e72da48ce4c6a9bd734b8d5b222943

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 dd8649d18a48308bb739dff49190ad9b81370c29

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 5d1d85ce11b8088181f22e86214aab4fa6b7d15c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 52988134fd40dc86e2a8248523ed907d3ad290c1

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 ea377e4e5fb581c2bbd6915c8da68ab08ffc026c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 3241977d2367a85121a089007b0b69923cb85f57

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 ba2bd19cb3d6117d1920002cd29418766fada0bb

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 ba2bd19cb3d6117d1920002cd29418766fada0bb

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/238
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/239

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.6.1 0a8c599a444022d02e4a37bc2a6cd68bbce12597

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/etcd release-3.5.0 5127c53df1f11c2a001046075a2d8ddce42e4d0c

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/234
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 8c9f07aa1eaa994fef407fae1ac10c6f1b001c16

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website 6d7ce8a01a043dc64aac3fbbd3f47d4acddb15be

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 5d1b12a6cb176f89fc1554c4bc2a97640b9ff89b

**Pull request merged**
