### PR TITLE
Release: v2023.01.05

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 06faa1fae9d9923b73b1c76952cd4d30414ac439

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise 762ebb4ebc8990cef04fdba99b4815baed2e01b8

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/cli/pull/174
/go github.com/stashed/cli stash.appscode.dev/cli 
/pr https://github.com/stashed/ui-server/pull/20
/go github.com/stashed/ui-server stash.appscode.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/ui-server 40819d4e2078291183f108a996e7786fe38bb7de

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli c8dabb7763dfbbb007b48f9c97711d06754043f0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 012c0bc1b6f06898f1a2b86b601c44d6ca290b03

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 c5a9100296e76ccc748fed8979ad5bff45e76188

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 a52a1e1ebbe0a69dd648136978405c15bb885fcd

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-15.1 c1411460fd542d536ee3ecb1773ad53c0b29e050

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 bbd9e54cb34ae1b46fb6df43394fc8274d4b0635

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 6a71a45ae97cc674304b0e497daafff98c027953

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 929f348ebc315a23683f7ad84883b9ec654caade

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 9288c6fb2fddfb255d5b164612e130fd77d58796

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 b121b8073283f48e3c8cf3af524f22dee30d8e2e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 29b29eb65f76a172d3fd36fc42f5fb09e530081f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.14.0 5130f2a4a08976c3120ff395cd73e5cb3935fd19

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 a94d6ef36b872ecaa84d5d6287b22e25ce13791a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-8.2.0 4807ee4960ee66435f86a8c5d0e3a8381e59a8b6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 c50a090471560c7eb2eaac6d684cfc7df283bbd5

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 583f64febc11714f48c8e9fbaa62d5873fc8c073

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 73bb53f02ae1c3f85792c67e047b997ceefe5bdb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 c49eec092a7a3bb339c70723a8a1e5bb6994acd0

**Comment by 1gtm** [comment]
/tagged github.com/stashed/elasticsearch
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 05ebbe8c141ea8c428c4123932c4389f631cafdc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 4b2ad2ab1d697ef3f7254666ee94321a3610c03f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 deba26e1872e3ec03f4669d6853615571c18736f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 5caeaeda0793fd05f3c019655a97d84a3061c76b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 dc6ef6349096d537472ce768ae567e2a5205f4be

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 78218444654ae6e6bc8cac824ad1bfb54305eb32

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 cd8f3b79ac3187386b98f5d030d5f62f18010178

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 a7b8fe3b0a3a3477f4bc34c6cfad145669764c1c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 8b5e5f2660effab9466ec7b662ec100da42f3493

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 ede5e29cee4285b5678a737cf023bc72c822f94f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 358bfa5c18e9aba941195b42e2117dfd66cb1880

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 7b684f624509b8760f64989adbce4cd9c51e4768

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 b63fcd290da356aed1d7d9b520c5f6f961444649

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 b63fcd290da356aed1d7d9b520c5f6f961444649

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 63f6fdc1418532837c14aed5ef0209efa35edc69

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 6c64379193b9273f061142fbb4445729af2743ad

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 cdd2b0f9a885834af911ebb9bff9469271b57661

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 74efb1f132822e165df1e287f0b4ce5c3506378d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 c86d3d8deed7025839d3ed553f4fd001fcf89f76

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 fea59b5378b5df29737afdd36a1d4285ee7a0f33

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-5.0.13 307f9a7fdd75ae24614198a8d44451ef93a24eeb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-7.0.5 92ab44b2dd0d18112cd6ef4a6dfebd11fdeb47d0

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/278
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/279

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 dceb6fd5b99788ab86bd4f0f44c80e7c857bb571

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.8.2 d374ae2f885481483ed6719a9121c8f27111e805

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/etcd release-3.5.0 523fc8f0761b0bc0991c457217fa61b68c82c7d0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/kubedump release-0.1.0 77c648c0c13a26f3bdb70de8c31fc8b6493f52ec

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/vault release-1.10.3 39030875b93b30cf9af4ee7c32f83c47c3ab4cf5

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/290
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 33a11ef1ddc6e97caad392b8b44e4acd78b83c97

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 8e569a135fdee662d09dac62b554de020754f8c8

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 42319de1e9cbe68a60259fd1caccd2d04815b20e

**Pull request merged**
