### PR TITLE
Release: v2022.06.21

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 76df41ccb320b735f465e92fc0cd0dd35281ad6e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise a6f2dc480054c72e3249cbf01b0f4656c5ae2e1e

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/cli/pull/164
/go github.com/stashed/cli stash.appscode.dev/cli 
/pr https://github.com/stashed/ui-server/pull/14
/go github.com/stashed/ui-server stash.appscode.dev/ui-server

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli 4942f3ec5562dacd74194be356269cb586a11525

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/ui-server dbe1690f880c51600b18543bdd1d237bc484f980

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 1db055d081da87e85cea649b51af07d0f0cfe056

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 61861efc65de7ff34b5908988d84b39f99594750

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 ade2cb882e0050371c954a968ada80bacae83e60

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 7a6cca43ca2d554228c0198d427f3c4170884664

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 a632d377718495e9aed782cf1df0f2800d32ede1

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 1fba7100b4cb2107e53dd8fdd2d93306b3e62831

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 a7c6504876c6a632fba47fbecef0269070bde9eb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 917089a972c4a63454b2c19a71a5bdfa26f61f49

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 2ab1c09a583fa024a11332800a44659ba3bf949c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 60daf578b2b46cb3624e4002f8d0bfac964e8539

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 08aa5cd001daa8e13e5e27e087e1680e2d3f94c4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 f71cc84e999f6338b201a51a8141e2c9f8f23599

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/elasticsearch f71cc84e999f6338b201a51a8141e2c9f8f23599
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/ready-to-tag github.com/stashed/elasticsearch 60daf578b2b46cb3624e4002f8d0bfac964e8539
/ready-to-tag github.com/stashed/elasticsearch 2ab1c09a583fa024a11332800a44659ba3bf949c
/ready-to-tag github.com/stashed/elasticsearch a7c6504876c6a632fba47fbecef0269070bde9eb
/ready-to-tag github.com/stashed/elasticsearch 08aa5cd001daa8e13e5e27e087e1680e2d3f94c4
/ready-to-tag github.com/stashed/elasticsearch 917089a972c4a63454b2c19a71a5bdfa26f61f49
/pr https://github.com/stashed/elasticsearch/pull/1219
/pr https://github.com/stashed/elasticsearch/pull/1220
/pr https://github.com/stashed/elasticsearch/pull/1221
/pr https://github.com/stashed/elasticsearch/pull/1222
/pr https://github.com/stashed/elasticsearch/pull/1223

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 6d92e35fa7fbcc777dd03d67a343141c010b5587

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-8.2.0 e302638501519e60305966f81ee1a0768b52cd04

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.14.0 49ba85f788e83bec1425e9d75fc69baf2e8f494b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 9ed8203dd665879945b90643acc79a1da28dbd00

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 c0cb607a3297358cbe94db51ef7f788ab5586ba6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 b9ea05bda4d62dea2be2bc23671e1db518f6898c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 b41ddb463e2b5ba4acdab58c3257c61ad9654bab

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 687f7d8f2f90d0ff878a2f308f33e018c9cefdc5

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 252b5708e9a9a5553fdd1ca9bd7291dbdc9552fc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 da8cc237eed4ed3bdac0eea31a250108228314ab

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 f30c6a13117c5bfd469f1e01b17c4c9e22a85606

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 4c92d8a325d5b27bdd691aab7b057647b7812d07

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 104d28bdf0e7c4dee420ea7de74e640f4243130e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 fb5eb4550b2e0cf4747d1500e2e6a05f38748e98

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 40168c4405512c9ae7efc4976564c847096b0c67

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 ba6f8429b7c4bf1dee7a7ea5f7aeef3e81820d9d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 c2d3d5929ef4139865204964d2cada160c523bb9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 0b2d6ec794164cf443f99286c0c49f6754e6cdf3

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 6788bc232f186e4a2a8fe2b86679150db6637d5e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 00a92f317b6a99f4e08086cb9fbf5966ff37176f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 75a46ecdaf0956f9a232cb5fef396b409c64ab35

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-5.0.13 2d26534b8f0092f1dcb6197467a57eda2e6a53f2

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 e9528e15c44093d120c651677ba1741f03b26c75

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/261
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/262

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 e02373e508e67dc8248f71d9379934e56011631a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.6.1 45e3eb59bda7a5e0311e5244b040898e90dddc47

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.8.2 b2540f1cbd878906f7ba7014a7c8e40219f11443

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/nats release-2.8.2 b2540f1cbd878906f7ba7014a7c8e40219f11443

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/kubedump release-0.1.0 8b71a1873f19d4686005972ccf2c714da559e564

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/263
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 38ca633b39833bb724c9b9fb4b1c238c5bb9f2ad

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 38ebc91010898fe853eed63e045da54e94768386

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website c08578556eae57a2931c4bc58842371293539ddd

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 5e1ffa073059c2feb27c0b6bbce4e21f87c0942e

**Pull request merged**
