### PR TITLE
Release: v2021.11.24

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 56eeababb207ec3f9b25b4393c3e103655099ca7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise 85b094e24a78ec970e00c1e0f0116fb4da74077e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/stash-enterprise 85b094e24a78ec970e00c1e0f0116fb4da74077e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli 7060e6f2eabc91332c012e231b0ad01013458095

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 ebdef975a3628e40c82ec7fe848148766f8f9252

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 42c89586f07c03715dfb85dd43c80cbacf99f630

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 8bfeb53851b6e9957258fb00bf510a81c74193a3

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 94c0d679f6a4b553d4107c93f841c4742ae5b0e6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 b2ab0cec9e0cccd9f5c89b3dc31e6ae4edcedf38

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 c98dd3faf0e7c8a2a63109adbb3754dc31ee2f80

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 0e14411832d9204bffcab07cb53f661f42c6fe58

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 d4201b7e8735a6be21501462c38fa2b39116e53a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 c253b5d28b99cf8f1db0d2458db05282aa96d6c4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.14.0 2be231a184d55150cc32445acb739f8b56c24406

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 7d7da2027b2bc52ab257ba277a6953c88c2e32ef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 5ba72d614a83e7eb34adb0ca3eecaf5a4e464cec

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 35ef5d4963bf4885ca906cf786a10a76b70d2eef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 7ddc15df3f03b702743b8c88654f8b5f30e81473

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 7ddc15df3f03b702743b8c88654f8b5f30e81473

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/elasticsearch 0e14411832d9204bffcab07cb53f661f42c6fe58
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/ready-to-tag github.com/stashed/elasticsearch 5ba72d614a83e7eb34adb0ca3eecaf5a4e464cec
/ready-to-tag github.com/stashed/elasticsearch d4201b7e8735a6be21501462c38fa2b39116e53a
/ready-to-tag github.com/stashed/elasticsearch 7d7da2027b2bc52ab257ba277a6953c88c2e32ef
/ready-to-tag github.com/stashed/elasticsearch 35ef5d4963bf4885ca906cf786a10a76b70d2eef
/ready-to-tag github.com/stashed/elasticsearch c253b5d28b99cf8f1db0d2458db05282aa96d6c4
/ready-to-tag github.com/stashed/elasticsearch 2be231a184d55150cc32445acb739f8b56c24406
/ready-to-tag github.com/stashed/elasticsearch 7ddc15df3f03b702743b8c88654f8b5f30e81473
/pr https://github.com/stashed/elasticsearch/pull/1067
/pr https://github.com/stashed/elasticsearch/pull/1068

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 5c1bde68ded4eff8d3c7051ddee680aa195a95bd

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 bebf02890aaab48bda8f315bc7de58b4ced551e1

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 6ecd2ef3b2f43d3ecbf4ba8919ef0be8df6b7bb7

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 57a441dd640c4d8caa4ffeaa05355ee9ac761817

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 d6a8db2de819675d20f8c512af6f4bdfec52ffe6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 46bb9249a2ede7b0e7b24f91e10ed8eabff17c4d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 1b56e13434692da5633f4254e4dcf67558cc6d87

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 db7f658c6bd7b07c7665fa357f234a5d16ee25b9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 23386af74dba891a834664ab231275be0aae1f35

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 7ae5a2ad1d88aeb54b47043001b05c8361a82dc3

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 9e7ba040ba1917e967357da641ae1a1ac072df35

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 9e7ba040ba1917e967357da641ae1a1ac072df35

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/mongodb bebf02890aaab48bda8f315bc7de58b4ced551e1
/go github.com/stashed/mongodb stash.appscode.dev/mongodb 
/ready-to-tag github.com/stashed/mongodb 57a441dd640c4d8caa4ffeaa05355ee9ac761817
/ready-to-tag github.com/stashed/mongodb 1b56e13434692da5633f4254e4dcf67558cc6d87
/ready-to-tag github.com/stashed/mongodb 46bb9249a2ede7b0e7b24f91e10ed8eabff17c4d
/ready-to-tag github.com/stashed/mongodb 9e7ba040ba1917e967357da641ae1a1ac072df35
/ready-to-tag github.com/stashed/mongodb 5c1bde68ded4eff8d3c7051ddee680aa195a95bd
/ready-to-tag github.com/stashed/mongodb db7f658c6bd7b07c7665fa357f234a5d16ee25b9
/ready-to-tag github.com/stashed/mongodb 23386af74dba891a834664ab231275be0aae1f35
/ready-to-tag github.com/stashed/mongodb 7ae5a2ad1d88aeb54b47043001b05c8361a82dc3
/ready-to-tag github.com/stashed/mongodb d6a8db2de819675d20f8c512af6f4bdfec52ffe6
/pr https://github.com/stashed/mongodb/pull/1350
/pr https://github.com/stashed/mongodb/pull/1351
/pr https://github.com/stashed/mongodb/pull/1352
/pr https://github.com/stashed/mongodb/pull/1353

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 e79762be3b12917009bf3280e8d0b2c360ca0a8f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 52d5104ba07546df4dc17e7c37f587a750c602b7

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 51c4a8dc067ae11e014c38cb19deb09820a3169f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 264b3f890385e1fdcf88c15ff017d4dab5510639

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 9364b2bf2bf4d5d3197e605a1bbce1a3dcd2a750

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 494bf1ba450e31b1ddd17c43f29f29c5df8ccafa

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 3cea90bb932c03433f51cf57a925114b4a549be8

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 c31170b2310c243e1a7b3845df563e228ceddb73

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 a27b1fb73a17546acd3f5f0e7828d70cc375a37a

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/230
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/231

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 72372b844962cf62c1a9041c10c8c7543d9c0abe

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.6.1 f806fbb0805a0ee94b639bea508a1653af5608f2

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/217
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 4dd855322b7731467c67792d66e9a1b5b01420e5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs d74e8a144ebad73f263541de674e3cefe53c59d1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website 1bf68e2936020af1f1dd8c2368f7cc9d5e8f6096

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 25853ad6e8d11ff2fd0142341284b8eaf057dc86

**Pull request merged**
