### PR TITLE
Release: v2024.8.27

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise 4f64305b65606e1d60dc702b2fb4238f44ebc4d9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli a4dd874ee96df7a298f16a1e7e710d639b3e0de0

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/ui-server 12b8cc878cda824fcebd7ac42ea0bfb442e2f8f9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 48a9b6190e9c4dcd9e663fc7612cbfbd58cd320b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 61302a0808f7d30eec03396702764034c0480f8f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 e159aa8e9b6fed6923d4a84e07915449ebab208f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 468a1f4543bdaeaed90c0440d6f19c51268d0fdb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 f6202ce4a791582a86d848a040be235aa16c0ceb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-15.1 0937f528cd2c6971a447320693e800f0ea68a8bd

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-16.1 b936987e19b91fb4a8d461398cd056bf64c22acc

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/elasticsearch/pull/1547
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/pr https://github.com/stashed/elasticsearch/pull/1548
/pr https://github.com/stashed/elasticsearch/pull/1549
/pr https://github.com/stashed/elasticsearch/pull/1550
/pr https://github.com/stashed/elasticsearch/pull/1551
/pr https://github.com/stashed/elasticsearch/pull/1552
/pr https://github.com/stashed/elasticsearch/pull/1553
/pr https://github.com/stashed/elasticsearch/pull/1554
/pr https://github.com/stashed/elasticsearch/pull/1555
/pr https://github.com/stashed/elasticsearch/pull/1556
/pr https://github.com/stashed/elasticsearch/pull/1557

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 022bfe288f888f236937d0192d2c388aed447bef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 a1e71bca2b953a2c5dcd758d301ce15880f460fa

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 590c441108a39c9ad455250ac350abb4ac435647

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 0e8791407fc538332e345d1395aa688c971654c4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 65c68556313ed7798b39a879d73a81823df0f45b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.14.0 43d959e5e2d84a41721a02d85c7d25e042fa7818

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 83fbb80a5cfd26290340a27557137865522194b4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-8.2.0 def1a44b46269e8b3dcf97761fd1f5c800a87240

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 5659abd7af4d958ff87254d1bd2169f4fb05436e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 855e9eb6ef03a72248e13f7562a6107c70a98add

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 852d1338f86c9a047e54a8accb1aae1d3fefdb3a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 8098d72f920ec279f1b4d881119c8453cf64dfc6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 de6e934e699e3b3ed748afbfa0cd667cfaa9c908

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 864e08935bdcaea115a31f9028f143d0dae4802d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 ca4a260f53ccf603274e621aa8b4dfeef84464b6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 e872ccab08031a04fc1ad85bd7259f2c995a8a28

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 02f6b9fec33934da1b12e4c097e32f62d9b522e7

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 04b231f7ad771e363616ea55cafb6cc30001332b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 5ce8589aa54f46f337005e9741dae578acb1f5f6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 4e0a833c6c80031e93dcce8e5cca55a3dceeed45

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.15 e075d41a05e899ef576ca2c2c5e9646c472c2a36

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 d3add779e1cbc4881b623ec56fa84d9832060a65

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-6.0.5 c5810d8d2bcd998c9ba49148d28b670d343b0e45

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 dc20d8fa0b9991bcbede6f5e6a45cc8e07415e57

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 9af04bf3834d42e461b2d1d1ee5dd367bfaa8680

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 05d3f4a39b39c20168b0d196d364cdd3ebb7b0c4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 3e2f7a10922ac1dda8fd4e8ff889568fbc905690

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 b674f8ec0fdb213b460ce3bae93c3e4118656861

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-5.0.13 8a1d96274a4cae2cb1af9a86efedb8b374dea4d9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 5b9b074f23f1f66d6b27fc7a401ea6078d8db2bc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-7.0.5 e690a70d2eebfd5dfd9fce37f9fc2941ca619019

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/322
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/323

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 fd5e210495836475d82805078638d63d3b5d2e3f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.8.2 a903d630aeb5ec2e451caed4c553037d5be24f6f

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/nats release-2.6.1 58b60c88e9765b02ebb41bb0038de1b73b6f36ed

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/etcd release-3.5.0 901d0a414e4f193086cc50eb80992caa72f1a6d3

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/kubedump release-0.1.0 f2c07a3a237b318665f6a7b17c793eeaf69ceb90

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/vault release-1.10.3 21d5420adffc0ce47e7c52a79ae63592b996cb56

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/343
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 7f7b18f1fe7dff7c07ac6419a7138c00e390c685

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 00ce37de1fbee47776492224f02fbda72a85a776

**Pull request merged**
