### PR TITLE
Release: v2020.10.21

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash ab872821093829d3eb43cc4e231c8f06b584ed3d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/stash-enterprise 371a703593dc19cd04e41858ed8a76fd428c975b

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli 1b821c827c46df7ed1049d303d1346b501f9f771

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 f6ceacc75a485a5591936c30db054913aaa01272

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 bc318b1a34ac5e93280996cf0e716867b469319e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 03355e3e28da6b9a17f454ef1f45cee703c4e34c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 3ecdb2c47441c9b340fed19cc9350535322c5474

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/elasticsearch/pull/381
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/pr https://github.com/stashed/elasticsearch/pull/382
/pr https://github.com/stashed/elasticsearch/pull/383
/pr https://github.com/stashed/elasticsearch/pull/384
/pr https://github.com/stashed/elasticsearch/pull/385
/pr https://github.com/stashed/elasticsearch/pull/386
/pr https://github.com/stashed/elasticsearch/pull/387
/pr https://github.com/stashed/elasticsearch/pull/388
/pr https://github.com/stashed/elasticsearch/pull/389

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 85da76477a95bcf764e44830f649396039bbfd45

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 e811b13c39fd3933c4d3fd82fd8a30fbbb5fe089

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 4ae76515094b86374c4992885957addb189f8ec1

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 25d05288dd866b66be2f77a0fb3de734c6370206

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 6186f5a3133921f129ef267f13075623e35dc532

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 2cb12c4cd17496dd2de1460df7932a35e5bc8d08

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 121adfc8072bf6c66dba6f2e742c57c4eb67189d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 827b433fc6f5abdedbc76d01aad3d388912d738c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 68276550da86f391b9c1385a7493483bed2617cf

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 bfdd9972c7ae4f0a7567ef14f2c1b3cec57d116d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 9255e7b5ab0523c8d03a80aa693059febbfceb65

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 92d7be92e52bd65b8aabe962b53e524596c35b12

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 37ee960a7c20b258106b0093811601d95c2cdf72

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 5dc82c7f11d1539d6a4debf8bdab51db9d1a66e7

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 7d17e60dfbfe935495f7716eae82d2780ecab8e2

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 90d2a873a465cc04e9d311053ec9066a810f0f7e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 54a9e1ce738ab258cc12e978c46eeb46d0b0448f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 0894946bef9e93063f9b37be81761a757cbf732f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 f613ba528b270633627de36acefba8afc60ffdb9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 8fffb5801a993b2913ce562d9bf0803ca106e49c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 c6bebdee8e23e27fa0dd36bb6b221bd89e0b4447

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 07d878cc16d6514438e1c1a6fd900d14fa21a725

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/95
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/96

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 6ec4bc6b320741f085988f653589b49c01759234

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/116
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 5bc51f33fe1ba728d6e7f55882bf110772e485a6

**Comment by tamalsaha** [comment]
trigger

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/catalog 0e40f7129f9fd879cfbb9a9317ede2b177b87d8d

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs d43834f1aab42a7dd0d0d313f7ad4f503d1fe3a7

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website 35678d62f87a1cca89d5f1ad0d073ba9d66166b9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 1d12a9a4a1e5f19ebefa80e2f64952782a58ef2b

**Pull request merged**
