### PR TITLE
Release: v2024.12.18

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash a4703c429ec70c32596f2c38d3c9a87d0ed2846c

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/enterprise bd5b45826df9d386722c0f3a11561f97c48789ff

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/ui-server c9376e315e571d2b3d0c1477ce8589d2c7a35796

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli 9e67374807a8c80540ed5b3d35ed9b590e502a3f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 431f2f1083d4d1863deeb93fcab5411d9856c60e

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 aa4657a6a52dc219a13f6bc914d6b78b3a771977

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-14.0 aaaebf71024d245b632c53ab78715864cdb93614

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-15.1 c28f4b49f19cc59b5bae6aec1469d707de44f47c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-16.1 b78b632275879a238aff6e2ade2f8706417b6970

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 3bae251eafc6eca06d373a0ddb72c3e2782b90cc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 998cba50a3a9e2aff7ab3d8f055de11895a7317b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 529981a3174e3dbe480b96d8b94d8bcc2629bcff

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 529981a3174e3dbe480b96d8b94d8bcc2629bcff

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-17.2 62ae3e1a1306591c78daf4d2eb4c79ae7bd3b2c1

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/elasticsearch/pull/1579
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/pr https://github.com/stashed/elasticsearch/pull/1580
/pr https://github.com/stashed/elasticsearch/pull/1581
/pr https://github.com/stashed/elasticsearch/pull/1582
/pr https://github.com/stashed/elasticsearch/pull/1583
/pr https://github.com/stashed/elasticsearch/pull/1584
/pr https://github.com/stashed/elasticsearch/pull/1585
/pr https://github.com/stashed/elasticsearch/pull/1586
/pr https://github.com/stashed/elasticsearch/pull/1587
/pr https://github.com/stashed/elasticsearch/pull/1588
/pr https://github.com/stashed/elasticsearch/pull/1589

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 fa5b7b2f24cf38f77bbb69f25489a376e1e8550b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 a88234a33a951ceb88c951571c2bb2a85edf595a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 a56523b929fb93e4c2ee64fb80371f341288a958

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 542f3af69ce84ce38332b6f0ab388e08264bc237

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 8432af1efc13dac42cdeb6830a36de79e8464e9d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 f6fc183cb476c96cc56d245fe7866674bcc4c5ef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 20d1e6717eceb78c297f11cca383937c56393723

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-8.2.0 22c08e5eaa6396cbf7d370f85342aa419d78a782

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.14.0 123a2ac843c4a5e819ede6692a9224c0614e76be

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 b99e6dd1098169f3ab4d5ae9410a8ca39003ee31

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 5697da70e0610761b7f850d2c3e828578461fc08

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 1f742d4bb1820d6fbc2234cd05752b9b5b334b55

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 6337c1274dcda6bc485a727d4cd8b05a923eb6c4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 ecfd742c6123ea8082e3935f3b635924cbd27ff0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 152dd1281594754d022b0c14be5a5cdfd55d629f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 39b9cd2472b2cbef1cc3351df2717bdf7416981a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 3eb3037d8b46039955794b16ec54235cdda17292

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 34588eaa2d1c5bcb0224233ecd69e45617058e28

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 21242246a607c66368978d93dde8672da9701c4d

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.4.6 5e51465019404ce84f53dd63defd7fd8b2050d89

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.3 537a68633d9f388633b455bacf3e3075abdfb2ac

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-5.0.15 d80984a1871306761ae9db01d1ae2a543005d9d4

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-6.0.5 bb7a2e10e4bb0c7188398843d8756053909a8644

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 58817a8ae4f1a6812e4486ae5e34450cea33429b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 c600101a69eb977a57d5801b578fefcd7610a104

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 d86ac5d7614ddf0b5c2a95517176c7b77f785d5b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 683a19f132ffd8a29d0354e48af4a8f329699e12

**Comment by tamalsaha** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 683a19f132ffd8a29d0354e48af4a8f329699e12

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 dbc3a4e6ad29ff3468b5dca57fe152d8f66b83ca

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-5.0.13 0eb9fcefc25b037a61478eba9c768d68bc8dab48

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-6.2.5 8cadd6c1d26547027670e5b1a637234e30d92b7a

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/redis 0eb9fcefc25b037a61478eba9c768d68bc8dab48
/go github.com/stashed/redis stash.appscode.dev/redis 
/ready-to-tag github.com/stashed/redis 8cadd6c1d26547027670e5b1a637234e30d92b7a
/pr https://github.com/stashed/redis/pull/246
/pr https://github.com/stashed/redis/pull/247

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/redis release-7.0.5 e3ac0a9325e699cbc2a0f8977230cc02ebad1dc8

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/percona-xtradb/pull/329
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb 
/pr https://github.com/stashed/percona-xtradb/pull/330

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 a27e90574edaa4f4fd606bb63ff48182ee20193b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.8.2 dae9f36b9ac593a6a6a905aacf7bcc976e8b30a5

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/nats release-2.6.1 434cc9a3740e5eb143eb77704391fc85993a6098

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/etcd release-3.5.0 5e4749aed3dad04922369365b0a9651db36e0773

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/kubedump release-0.1.0 7b4ed69a758ad9e7b862900b1565bb1431bcf4cc

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/vault release-1.10.3 49099011df4056fb5b2afb3341dd55666d7ce73d

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/381
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 848c27da44364ad10880da35bd9fadf029953132

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs d43734cf8aea7a8487e1dc552715952a7dab267e

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website d711b1270d3d669488ede2d6518f5720f542fe1f

**Pull request merged**
