### PR TITLE
Release: v2021.04.09

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/stashed/apimachinery
/go github.com/stashed/apimachinery stash.appscode.dev/apimachinery

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/stash 50f8a075a8bfefed3c2397d4fecbaf5631871fa5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/appscode/stash-enterprise 8692accbb8d4c995c38ccc47d3f20798b3f2c3a1

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/cli 9c95d5ebf650e5785bbae70608464d2d0cbf5649

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-12.4 582fb72585e9334b4df09841d8df94c9ae5874ef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-10.14 6e5e02c0b94a45f1b01a5d0347163fb62a17c7b0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-9.6.19 952e50a2dcae93d3370184d0af39dc3b2148e967

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-13.1 2d214d1541963ed1593d78bb3fb3e21ae144bc25

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/postgres release-11.9 ccf2b20eafd9a2f686b3f878e9b233f4da49f71c

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/elasticsearch/pull/735
/go github.com/stashed/elasticsearch stash.appscode.dev/elasticsearch 
/pr https://github.com/stashed/elasticsearch/pull/736
/pr https://github.com/stashed/elasticsearch/pull/737
/pr https://github.com/stashed/elasticsearch/pull/738
/pr https://github.com/stashed/elasticsearch/pull/739
/pr https://github.com/stashed/elasticsearch/pull/740
/pr https://github.com/stashed/elasticsearch/pull/741
/pr https://github.com/stashed/elasticsearch/pull/742
/pr https://github.com/stashed/elasticsearch/pull/743

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-5.6.4 3267fe9758a8be6528c9b0cb11d75cfd8f3a2cad

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.3.0 6018f25920338fd05daad17cb7c19aba1859ce8a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.2.4 3ff81b34c423f29b8e07c111b4fbf2b491842cff

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.5.3 c095b0af2c2033135b102a543560ee5f4f24c005

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.4.0 cf4b7e4acba0d150f7ba50824b5cc7fabb281e08

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.2.0 c377796920423bd6d3f46da3ee6c94e5de26cc24

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-7.3.2 0d2ba065ecde63a52a88e25c28b52571a599b471

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/elasticsearch release-6.8.0 0bce530dd9e1e2dda530dee1bde39275d131fddb

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.22 cf3b8d58a176dd6bd992a3e22066f9fb04f8dba5

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.11 7c9f57cfd86b93552850157c3fc98fd63bd1538b

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.8 b8e59d9f9c9380cac437cb647eddbc80e14db0e0

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.3 9ec6ccd007b433268fd9ddcb888b1dcb5ac68aa6

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.4.17 c330b36d813668301ad9f7fa4109837be2d54677

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-3.6.13 bf2677dfd81b76c4c64ea740d90a7c97384741ef

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.13 53eb5dc1ed7c416bec44c69743c13efb15de7d73

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.0.5 4976afaf38965d9da0ece976ea02069729927698

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.7 b8323b2feded68e22cda518ff8325d5031bcd61f

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.1.4 a496100936196bc5eb4ac37e301bbb3bfd3d30b1

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mongodb release-4.2.3 4e45e4ca7fada26354bd421001b7b14d073f4cf4

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/mongodb c330b36d813668301ad9f7fa4109837be2d54677
/go github.com/stashed/mongodb stash.appscode.dev/mongodb 
/ready-to-tag github.com/stashed/mongodb cf3b8d58a176dd6bd992a3e22066f9fb04f8dba5
/ready-to-tag github.com/stashed/mongodb bf2677dfd81b76c4c64ea740d90a7c97384741ef
/ready-to-tag github.com/stashed/mongodb b8e59d9f9c9380cac437cb647eddbc80e14db0e0
/ready-to-tag github.com/stashed/mongodb 7c9f57cfd86b93552850157c3fc98fd63bd1538b
/ready-to-tag github.com/stashed/mongodb 9ec6ccd007b433268fd9ddcb888b1dcb5ac68aa6
/ready-to-tag github.com/stashed/mongodb 4976afaf38965d9da0ece976ea02069729927698
/ready-to-tag github.com/stashed/mongodb 53eb5dc1ed7c416bec44c69743c13efb15de7d73
/ready-to-tag github.com/stashed/mongodb a496100936196bc5eb4ac37e301bbb3bfd3d30b1
/ready-to-tag github.com/stashed/mongodb b8323b2feded68e22cda518ff8325d5031bcd61f
/ready-to-tag github.com/stashed/mongodb 4e45e4ca7fada26354bd421001b7b14d073f4cf4
/pr https://github.com/stashed/mongodb/pull/886

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.21 a1fd10f20ae3832f16c299d7ef001eea302b0ebd

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.14 ef07360f2f5e33bac13f77adb2cb1b832686687a

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-5.7.25 43e5c9f8718beaa5160697c963915e8ed5ec6b1c

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mysql release-8.0.3 363bcab90cf0bee4a821d3b4f06a69c50cf1d1e9

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/mariadb release-10.5.8 cb2457b291c0f1fa31cef3a322c3e09bc1c093bd

**Comment by 1gtm** [comment]
/cherry-picked github.com/stashed/percona-xtradb release-5.7 f9b4dc869e60805d8ff570fc6072df1dade4824e
/tagged github.com/stashed/percona-xtradb
/go github.com/stashed/percona-xtradb stash.appscode.dev/percona-xtradb

**Comment by 1gtm** [comment]
/pr https://github.com/stashed/installer/pull/172
/go github.com/stashed/installer stash.appscode.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/installer 39bdc8e5358f75d62e86225684e225b262f66366

**Comment by tamalsaha** [comment]
/ready-to-tag github.com/stashed/installer 39bdc8e5358f75d62e86225684e225b262f66366

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/docs 3dee959dfab602dd884e924ca758b14b68e386ce

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/website 29ab86c4f69d0a6f3b01301d28b9dba546d6efd5

**Comment by 1gtm** [comment]
/ready-to-tag github.com/stashed/bundles 6fa334e942772d7ca05265d0361f5707364dccc6

**Pull request merged**
